In [39]:
import tensorflow as tf
from tensorflow import keras

In [40]:
x = tf.random.normal([2, 3])

In [41]:
model = keras.Sequential([
    keras.layers.Dense(2, activation='relu'),
    keras.layers.Dense(2, activation='relu'),
    keras.layers.Dense(2)
])
model.build(input_shape=[None, 3])
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_16 (Dense)             (None, 2)                 6         
_________________________________________________________________
dense_17 (Dense)             (None, 2)                 6         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [42]:
for p in model.trainable_variables:
    print(p.name, p.shape)

dense_15/kernel:0 (3, 2)
dense_15/bias:0 (2,)
dense_16/kernel:0 (2, 2)
dense_16/bias:0 (2,)
dense_17/kernel:0 (2, 2)
dense_17/bias:0 (2,)


In [43]:
a = tf.linspace(-6.,6,10)

In [44]:
tf.sigmoid(a)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00247262, 0.00931596, 0.0344452 , 0.11920292, 0.33924368,
       0.6607564 , 0.880797  , 0.96555483, 0.99068403, 0.9975274 ],
      dtype=float32)>

In [45]:
x = tf.random.normal([1,28,28])*5
tf.reduce_min(x), tf.reduce_max(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=-18.28728>,
 <tf.Tensor: shape=(), dtype=float32, numpy=13.709105>)

In [46]:
x = tf.sigmoid(x)
tf.reduce_min(x), tf.reduce_max(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.1427088e-08>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999989>)

In [47]:
logits = tf.random.uniform([1,10],minval=-2,maxval=12)

In [48]:
prob = tf.nn.softmax(logits,axis=1)

In [49]:
tf.reduce_sum(prob,axis=1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.99999994], dtype=float32)>